# Generated by Django 5.1.4 on 2026-09-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0001_initial"),
        ("nss_units", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="nss_units.college",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="nss_units.university",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="nss_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to="nss_units.nssunit",
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="volunteers", to="events.eventskill"
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
