# Generated by Django 5.1.15 on 2026-09-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='location_source',
            field=models.CharField(blank=True, choices=[('DEVICE', "Uploader's device"), ('EXIF', 'Photo metadata'), ('', 'Not available')], max_length=10),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
