# Generated by Django 5.1.4 on 2026-09-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_CREATED", "Application created"),
                            ("APPLICATION_APPROVED", "Application approved"),
                            ("APPLICATION_REJECTED", "Application rejected"),
                            ("APPLICATION_WAITLISTED", "Application waitlisted"),
                            ("APPLICATION_CANCELLED", "Application cancelled"),
                            ("EVENT_APPROVED", "Event approved"),
                            ("EVENT_REJECTED", "Event rejected"),
                            ("EVENT_REMINDER", "Event reminder"),
                            ("EVENT_UPDATED", "Event updated"),
                            ("ATTENDANCE_CONFIRMED", "Attendance confirmed"),
                            ("CERTIFICATE_GENERATED", "Certificate generated"),
                            ("NGO_VERIFIED", "NGO verified"),
                            ("NGO_STATUS_CHANGED", "NGO status changed"),
                            ("NSS_UNIT_VERIFIED", "NSS unit verified"),
                            ("NSS_UNIT_STATUS_CHANGED", "NSS unit status changed"),
                            ("NSS_INVITATION", "NSS invitation"),
                            ("GROUP_APPLICATION", "Group application"),
                            ("EMERGENCY_REQUEST", "Emergency request"),
                            ("FEEDBACK_REQUIRED", "Feedback required"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Frontend path, e.g. /events/12",
                        max_length=300,
                    ),
                ),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read"],
                        name="notificatio_recipie_6e3964_idx",
                    )
                ],
            },
        ),
    ]
