"""AI provider abstraction.

`RuleBasedAIProvider` is the default and works fully offline. Every number it
produces is a transparent calculation over data in the database; it is NOT a
trained machine-learning model, and responses say so.

`OpenAIProvider` / `GeminiProvider` implement the same interface. They use the
external LLM only for the two text tasks (categorisation, summaries) and fall back
to the rule-based implementation for everything else or on any error.
"""
from __future__ import annotations

import json
import logging
import re
from collections import defaultdict
from decimal import Decimal

from django.conf import settings
from django.db.models import Avg, Count, Q, Sum

from core.utils import haversine_km

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "Generated by a transparent rule-based scoring model using data recorded on this platform. "
    "It is decision support, not an objective judgement; please review before acting."
)

# ---------------------------------------------------------------- categorisation keywords
THEME_KEYWORDS = {
    "ENVIRONMENT": [
        "tree", "plantation", "plant", "cleanup", "clean-up", "clean up", "beach", "waste", "recycl", "plastic",
        "environment", "green", "garden", "mangrove", "river", "lake", "climate", "cleanliness", "swachh", "compost", "sapling",
    ],
    "COMMUNITY": [
        "community", "food drive", "food distribution", "elderly", "old age", "orphan", "shelter", "disaster", "relief",
        "flood", "village", "slum", "homeless", "donation drive", "clothes", "rural", "construction", "shramdaan",
    ],
    "HEALTH": [
        "blood", "donation camp", "health", "medical", "hygiene", "vaccin", "dental", "eye camp", "checkup", "check-up",
        "sanitation", "nutrition", "yoga", "fitness", "mental health", "first aid", "thalassemia", "menstrual",
    ],
    "EDUCATION": [
        "teach", "tutor", "literacy", "school", "education", "mentor", "coaching", "reading", "library", "classes",
        "students", "computer literacy", "digital literacy", "workshop", "skill training",
    ],
    "AWARENESS": [
        "awareness", "campaign", "rally", "street play", "nukkad", "road safety", "voter", "drug", "anti-", "gender",
        "rights", "cyber safety", "seminar", "pledge", "poster", "helpline",
    ],
}
THEME_TO_ABP = {"ENVIRONMENT": "ABP1", "COMMUNITY": "ABP1", "HEALTH": "ABP2", "EDUCATION": "ABP2", "AWARENESS": "ABP2"}
UNIVERSITY_HINTS = ["university level", "university-level", "inter-college", "intercollegiate", "inter college", "university camp"]
COLLEGE_HINTS = ["college level", "college-level", "on campus", "campus drive", "college day", "within the college"]

SLOT_LABELS = {"MORNING": "Morning (before 12:00)", "AFTERNOON": "Afternoon (12:00–17:00)", "EVENING": "Evening (after 17:00)"}
WEEKDAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
WEEKDAY_CODES = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]


def _slot(t):
    if t.hour < 12:
        return "MORNING"
    if t.hour < 17:
        return "AFTERNOON"
    return "EVENING"


class AIProvider:
    name = "base"

    def categorize_event(self, title: str, description: str) -> dict:
        raise NotImplementedError

    def recommend_units(self, event, limit: int = 10) -> list[dict]:
        raise NotImplementedError

    def estimate_turnout(self, event) -> dict:
        raise NotImplementedError

    def suggest_datetime(self, category: str) -> dict:
        raise NotImplementedError

    def summarize_event(self, event) -> dict:
        raise NotImplementedError


class RuleBasedAIProvider(AIProvider):
    name = "rule_based"

    # ------------------------------------------------------------ 1. category suggestion
    def categorize_event(self, title, description):
        text = f"{title} {description}".lower()
        scores, matched = {}, {}
        for theme, words in THEME_KEYWORDS.items():
            hits = [w for w in words if w in text]
            # title matches count double – the title is the strongest signal
            title_hits = [w for w in words if w in (title or "").lower()]
            scores[theme] = len(hits) + len(title_hits)
            matched[theme] = hits
        best_theme = max(scores, key=scores.get)
        total = sum(scores.values())
        reasons = []
        if scores[best_theme] == 0:
            theme, category, confidence = "OTHER", None, 0.0
            reasons.append("No known theme keywords found; please choose the category manually.")
        else:
            theme = best_theme
            category = THEME_TO_ABP[theme]
            confidence = round(scores[best_theme] / total, 2)
            reasons.append(f"Matched {theme.lower()} keywords: {', '.join(matched[theme][:6])}.")
            reasons.append(f"{theme.title()} maps to {category[:3]} {category[3:]} under the NSS Area Based Project rules.")
        if any(h in text for h in UNIVERSITY_HINTS):
            category = "UNIVERSITY_EVENT"
            reasons.append("Description mentions a university-level / inter-college activity.")
        elif any(h in text for h in COLLEGE_HINTS):
            category = "COLLEGE_EVENT"
            reasons.append("Description mentions a college-level / on-campus activity.")
        return {
            "category": category,
            "theme": theme,
            "confidence": confidence,
            "theme_scores": scores,
            "reasons": reasons,
            "method": "keyword_rules",
            "disclaimer": DISCLAIMER,
        }

    # ------------------------------------------------------------ 2. NSS-unit recommendation
    def recommend_units(self, event, limit=10):
        from attendance.models import Attendance
        from events.models import ApplicationStatus, EventApplication, EventStatus
        from nss_units.models import NSSUnit, VerificationStatus

        weights = dict(settings.AI_MATCH_WEIGHTS)
        wsum = sum(weights.values()) or 1
        weights = {k: v / wsum for k, v in weights.items()}
        max_km = settings.AI_MAX_DISTANCE_KM

        approved = EventApplication.objects.filter(event=event, status__in=[ApplicationStatus.APPROVED, ApplicationStatus.COMPLETED]).count()
        needed = max(event.maximum_volunteers - approved, 1)
        required = set(event.required_skills.values_list("name", flat=True))
        weekday = WEEKDAY_CODES[event.date.weekday()]

        # Volunteers already committed to another event on the same date are not "available".
        busy = set(
            EventApplication.objects.filter(
                event__date=event.date, status=ApplicationStatus.APPROVED,
                event__status__in=[EventStatus.APPROVED, EventStatus.ONGOING],
            ).exclude(event=event).values_list("volunteer_id", flat=True)
        )
        already = set(EventApplication.objects.filter(event=event).exclude(status=ApplicationStatus.CANCELLED).values_list("volunteer_id", flat=True))

        units = NSSUnit.objects.filter(verification_status=VerificationStatus.VERIFIED).select_related("college")
        results = []
        for unit in units:
            members = list(
                unit.volunteers.filter(user__is_active=True).select_related("user").prefetch_related("skills")
            )
            member_ids = [m.user_id for m in members]
            reasons = []

            # Distance
            dist = haversine_km(event.latitude, event.longitude, unit.latitude, unit.longitude)
            if dist is None:
                distance_score = 0.5
                reasons.append("Location missing for event or unit – distance scored neutral (50).")
            else:
                distance_score = max(0.0, 1 - dist / max_km)
                reasons.append(f"{dist} km from the venue (scores 0 beyond {int(max_km)} km).")

            # Skills
            unit_skills = set()
            for m in members:
                unit_skills.update(s.name for s in m.skills.all())
            if required:
                covered = required & unit_skills
                skill_score = len(covered) / len(required)
                if covered:
                    reasons.append(f"Members cover {len(covered)}/{len(required)} required skills ({', '.join(sorted(covered))}).")
                else:
                    reasons.append(f"No members list the required skills ({', '.join(sorted(required))}).")
            else:
                skill_score = 1.0
                reasons.append("Event has no specific skill requirements.")

            # Availability
            available = [
                m for m in members
                if m.user_id not in busy and m.user_id not in already and (not m.availability or weekday in m.availability)
            ]
            availability_score = min(1.0, len(available) / needed) if needed else 1.0
            reasons.append(f"{len(available)} of {len(members)} members appear free on {WEEKDAY_NAMES[event.date.weekday()]} (event needs {needed} more).")

            # Historical attendance reliability (showed up vs. were approved, completed events only)
            past_apps = EventApplication.objects.filter(
                volunteer_id__in=member_ids, event__status=EventStatus.COMPLETED,
                status__in=[ApplicationStatus.APPROVED, ApplicationStatus.COMPLETED],
            )
            past_count = past_apps.count()
            if past_count:
                showed = Attendance.objects.filter(
                    volunteer_id__in=member_ids, event_id__in=past_apps.values("event_id"),
                    status__in=[Attendance.Status.PRESENT, Attendance.Status.LATE],
                ).count()
                attendance_score = min(1.0, showed / past_count)
                reasons.append(f"Members attended {showed} of {past_count} approved past registrations ({round(100 * attendance_score)}%).")
            else:
                attendance_score = 0.5
                reasons.append("No attendance history yet – reliability scored neutral (50).")

            # Interest / category match (+ previous participation in this category)
            if members:
                interested = sum(1 for m in members if event.category in (m.interests or []) or event.theme in (m.interests or []))
                interest_ratio = interested / len(members)
            else:
                interested, interest_ratio = 0, 0.0
            prior_same_cat = Attendance.objects.filter(
                volunteer_id__in=member_ids, event__category=event.category,
                status__in=[Attendance.Status.PRESENT, Attendance.Status.LATE],
            ).count()
            interest_score = min(1.0, interest_ratio + (0.2 if prior_same_cat else 0))
            reasons.append(
                f"{interested} members list {event.get_category_display()}/{event.get_theme_display()} as an interest"
                + (f"; unit has {prior_same_cat} past attendances in this category." if prior_same_cat else ".")
            )

            parts = {
                "distance": distance_score, "skills": skill_score, "availability": availability_score,
                "attendance": attendance_score, "interest": interest_score,
            }
            match = sum(parts[k] * weights.get(k, 0) for k in parts) * 100
            results.append({
                "nss_unit": unit,
                "match_score": round(match, 2),
                "distance_score": round(distance_score * 100, 2),
                "skill_score": round(skill_score * 100, 2),
                "availability_score": round(availability_score * 100, 2),
                "attendance_score": round(attendance_score * 100, 2),
                "interest_score": round(interest_score * 100, 2),
                "distance_km": dist,
                "available_volunteers": len(available),
                "reasons": reasons,
                "weights": weights,
            })
        results.sort(key=lambda r: r["match_score"], reverse=True)
        return results[:limit]

    # ------------------------------------------------------------ 3. turnout estimate
    def estimate_turnout(self, event):
        from attendance.models import Attendance
        from events.models import ApplicationStatus, Event, EventApplication, EventStatus

        registered = EventApplication.objects.filter(
            event=event, status__in=[ApplicationStatus.APPROVED, ApplicationStatus.COMPLETED]
        ).count()
        pending = EventApplication.objects.filter(event=event, status=ApplicationStatus.PENDING).count()

        def rate_for(qs):
            approved = EventApplication.objects.filter(
                event__in=qs, status__in=[ApplicationStatus.APPROVED, ApplicationStatus.COMPLETED]
            ).count()
            if not approved:
                return None, 0
            showed = Attendance.objects.filter(event__in=qs, status__in=[Attendance.Status.PRESENT, Attendance.Status.LATE]).count()
            return min(1.0, showed / approved), qs.count()

        completed = Event.objects.filter(status=EventStatus.COMPLETED).exclude(pk=event.pk)
        rate, n = rate_for(completed.filter(category=event.category))
        basis = f"{n} completed {event.get_category_display()} events"
        if rate is None:
            rate, n = rate_for(completed)
            basis = f"{n} completed events (no history for this category yet)"
        if rate is None:
            rate, n = 0.75, 0
            basis = "no completed events yet – using a default 75% show-up rate"
        expected = round(registered * rate)
        # Pending applicants are counted at half weight: roughly half get approved historically.
        expected_with_pending = round((registered + pending * 0.5) * rate)
        return {
            "registered_approved": registered,
            "pending_applications": pending,
            "historical_show_rate": round(rate * 100, 1),
            "expected_turnout": expected,
            "expected_turnout_including_pending": expected_with_pending,
            "range": [max(0, round(expected * 0.85)), min(event.maximum_volunteers, round(expected * 1.15) + (1 if expected else 0))],
            "capacity": event.maximum_volunteers,
            "basis": basis,
            "sample_size": n,
            "method": "historical_average",
            "disclaimer": DISCLAIMER,
        }

    # ------------------------------------------------------------ 4. best date/time
    def suggest_datetime(self, category):
        from attendance.models import Attendance
        from events.models import ApplicationStatus, Event, EventStatus

        events = Event.objects.filter(status=EventStatus.COMPLETED)
        if category:
            events = events.filter(category=category)
        events = events.annotate(
            approved=Count("applications", filter=Q(applications__status__in=[ApplicationStatus.APPROVED, ApplicationStatus.COMPLETED]), distinct=True),
            attended=Count("attendance_records", filter=Q(attendance_records__status__in=[Attendance.Status.PRESENT, Attendance.Status.LATE]), distinct=True),
        )
        buckets = defaultdict(lambda: {"events": 0, "approved": 0, "attended": 0})
        for ev in events:
            key = (ev.date.weekday(), _slot(ev.start_time))
            b = buckets[key]
            b["events"] += 1
            b["approved"] += ev.approved
            b["attended"] += ev.attended
        ranked = []
        for (wd, slot), b in buckets.items():
            if not b["approved"]:
                continue
            ranked.append({
                "weekday": WEEKDAY_NAMES[wd],
                "slot": slot,
                "slot_label": SLOT_LABELS[slot],
                "turnout_rate": round(100 * b["attended"] / b["approved"], 1),
                "avg_attendees": round(b["attended"] / b["events"], 1),
                "events_considered": b["events"],
            })
        # Rank by turnout rate, then by absolute attendance; require evidence.
        ranked.sort(key=lambda r: (r["turnout_rate"], r["avg_attendees"], r["events_considered"]), reverse=True)
        if not ranked:
            return {
                "suggestions": [
                    {"weekday": "Saturday", "slot": "MORNING", "slot_label": SLOT_LABELS["MORNING"], "turnout_rate": None, "avg_attendees": None, "events_considered": 0},
                    {"weekday": "Sunday", "slot": "MORNING", "slot_label": SLOT_LABELS["MORNING"], "turnout_rate": None, "avg_attendees": None, "events_considered": 0},
                ],
                "basis": "No completed events with attendance yet – weekend mornings are a common default for student volunteering.",
                "method": "historical_average",
                "disclaimer": DISCLAIMER,
            }
        return {
            "suggestions": ranked[:3],
            "basis": f"Based on {sum(r['events_considered'] for r in ranked)} completed events"
            + (f" in category {category}" if category else "") + ", ranked by attended ÷ approved.",
            "method": "historical_average",
            "disclaimer": DISCLAIMER,
        }

    # ------------------------------------------------------------ 5. post-event summary
    def event_facts(self, event):
        from attendance.models import Attendance, Feedback, VolunteerHours
        from events.models import ApplicationStatus

        att = Attendance.objects.filter(event=event)
        present = att.filter(status=Attendance.Status.PRESENT).count()
        late = att.filter(status=Attendance.Status.LATE).count()
        absent = att.filter(status=Attendance.Status.ABSENT).count()
        approved = event.applications.filter(status__in=[ApplicationStatus.APPROVED, ApplicationStatus.COMPLETED]).count()
        hours = VolunteerHours.objects.filter(event=event).aggregate(total=Sum("hours"))["total"] or Decimal("0")
        fb = Feedback.objects.filter(event=event).aggregate(avg=Avg("rating"), n=Count("id"))
        colleges = (
            att.exclude(status=Attendance.Status.ABSENT)
            .exclude(volunteer__profile__college__isnull=True)
            .values_list("volunteer__profile__college__name", flat=True).distinct()
        )
        return {
            "approved": approved, "present": present, "late": late, "absent": absent,
            "attended": present + late, "hours": float(hours),
            "avg_rating": round(fb["avg"], 2) if fb["avg"] else None, "feedback_count": fb["n"],
            "colleges": sorted(set(colleges)),
        }

    def summarize_event(self, event):
        f = self.event_facts(event)
        rate = f"{round(100 * f['attended'] / f['approved'])}%" if f["approved"] else "n/a"
        lines = [
            f"{event.title} ({event.get_category_display()}, {event.get_theme_display()}) was held on "
            f"{event.date:%d %b %Y} at {event.location}, organised by {event.organizer_display}.",
            f"{f['attended']} of {f['approved']} approved volunteers attended (show-up rate {rate}; "
            f"{f['present']} on time, {f['late']} late, {f['absent']} absent), contributing {f['hours']:.1f} volunteer hours.",
        ]
        if f["colleges"]:
            lines.append(f"Participating colleges: {', '.join(f['colleges'][:8])}{' and others' if len(f['colleges']) > 8 else ''}.")
        if f["avg_rating"]:
            lines.append(f"Volunteers rated the drive {f['avg_rating']}/5 across {f['feedback_count']} feedback responses.")
        if event.organizer_notes:
            notes = re.sub(r"\s+", " ", event.organizer_notes.strip())
            lines.append(f"Organizer notes: {notes}")
        return {"summary": " ".join(lines), "facts": f, "method": "template", "disclaimer": DISCLAIMER}


class _LLMProvider(RuleBasedAIProvider):
    """Shared behaviour for external LLM providers: text tasks go to the LLM, the rest stays rule-based."""

    def _complete(self, prompt: str) -> str:
        raise NotImplementedError

    def categorize_event(self, title, description):
        base = super().categorize_event(title, description)
        prompt = (
            "Classify this NSS volunteering event. Reply with JSON only: "
            '{"theme": one of ENVIRONMENT|COMMUNITY|HEALTH|EDUCATION|AWARENESS|OTHER, '
            '"category": one of ABP1|ABP2|COLLEGE_EVENT|UNIVERSITY_EVENT, "reason": short string}. '
            "ABP1 = environmental & community service; ABP2 = health, education & awareness.\n\n"
            f"Title: {title}\nDescription: {description}"
        )
        try:
            raw = self._complete(prompt)
            data = json.loads(re.search(r"\{.*\}", raw, re.S).group(0))
            if data.get("theme") in THEME_KEYWORDS or data.get("theme") == "OTHER":
                base["theme"] = data["theme"]
            if data.get("category") in ("ABP1", "ABP2", "COLLEGE_EVENT", "UNIVERSITY_EVENT"):
                base["category"] = data["category"]
            base["reasons"] = [f"LLM ({self.name}): {data.get('reason', '')}"] + base["reasons"]
            base["method"] = f"llm:{self.name}"
        except Exception:
            logger.exception("%s categorisation failed; using rule-based result", self.name)
        return base

    def summarize_event(self, event):
        base = super().summarize_event(event)
        prompt = (
            "Write a concise, factual 4-6 sentence post-event report for an NSS volunteering drive. "
            "Use only these facts; do not invent numbers.\n\n"
            f"Facts: {json.dumps(base['facts'])}\nTemplate summary: {base['summary']}"
        )
        try:
            text = self._complete(prompt).strip()
            if text:
                base["summary"] = text
                base["method"] = f"llm:{self.name}"
        except Exception:
            logger.exception("%s summary failed; using template", self.name)
        return base


class OpenAIProvider(_LLMProvider):
    name = "openai"

    def _complete(self, prompt):
        import requests

        if not settings.OPENAI_API_KEY:
            raise RuntimeError("OPENAI_API_KEY not configured")
        r = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {settings.OPENAI_API_KEY}"},
            json={"model": settings.OPENAI_MODEL, "messages": [{"role": "user", "content": prompt}], "temperature": 0.2},
            timeout=20,
        )
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"]


class GeminiProvider(_LLMProvider):
    name = "gemini"

    def _complete(self, prompt):
        import requests

        if not settings.GEMINI_API_KEY:
            raise RuntimeError("GEMINI_API_KEY not configured")
        r = requests.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/{settings.GEMINI_MODEL}:generateContent",
            headers={"x-goog-api-key": settings.GEMINI_API_KEY},
            json={"contents": [{"parts": [{"text": prompt}]}]},
            timeout=20,
        )
        r.raise_for_status()
        return r.json()["candidates"][0]["content"]["parts"][0]["text"]


PROVIDERS = {"rule_based": RuleBasedAIProvider, "openai": OpenAIProvider, "gemini": GeminiProvider}


def get_provider() -> AIProvider:
    name = (settings.AI_PROVIDER or "rule_based").lower()
    cls = PROVIDERS.get(name, RuleBasedAIProvider)
    if cls is OpenAIProvider and not settings.OPENAI_API_KEY:
        cls = RuleBasedAIProvider
    if cls is GeminiProvider and not settings.GEMINI_API_KEY:
        cls = RuleBasedAIProvider
    return cls()
