# Generated by Django 5.1.4 on 2026-09-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("nss_units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
                ),
                ("distance_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("skill_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "availability_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "attendance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("interest_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("available_volunteers", models.PositiveIntegerField(default=0)),
                ("reasons", models.JSONField(default=list)),
                ("provider", models.CharField(default="rule_based", max_length=30)),
                ("weights", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="events.event",
                    ),
                ),
                (
                    "nss_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="nss_units.nssunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "nss_unit"),
                        name="uniq_recommendation_event_unit",
                    )
                ],
            },
        ),
    ]
