# Generated by Django 5.1.4 on 2026-09-27 11:54

import certificates.models
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        db_index=True,
                        default=certificates.models.generate_certificate_id,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to=core.validators.SafeUploadTo("certificates"),
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        default=certificates.models.generate_verification_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("verify_url", models.URLField(blank=True, max_length=500)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="events.event",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "event"),
                        name="uniq_certificate_per_volunteer_event",
                    )
                ],
            },
        ),
    ]
